on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: Testing sencha install
    steps:
    - uses: stenjo/sencha-cmd@v1
    - uses: actions/checkout@v2

    - name: Testing sencha install
      run: sencha web -p 8080 start &
    - run: curl localhost:8080/index.html
    
