on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Install sencha
      uses: stenjo/sencha-cmd@v1
    - run: |
        pwd
        ls -al
    - name: Testing sencha install
      run: sencha web -p 8080 start &
